### ISSUE TITLE
Problem with starting the project

### ISSUE THREAD

**Issue by gregor-srdic** [GabrieleRomeo/ES6-Professional-starter-kit#6]
```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Nomnio\SeltronHome\GwdConfig\node_modules\keytar\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\grego_000\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\grego_000\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Nomnio\SeltronHome\GwdConfig\node_modules\keytar
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by GabrieleRomeo** [comment]
Hi @gregor-srdic 
please have a look at this discussion [https://github.com/nodejs/node-gyp/issues/809](https://github.com/nodejs/node-gyp/issues/809)
There are different solutions and suggestions about _node-gyp_'s rebuild issues
